### ISSUE TITLE
the version

### ISSUE THREAD

**Issue by zhl606** [73jn/ns3-plc-with-gnosis#1]
Hello! My ubuntu version is 18.04, and the version of ns3 is ns-3.15. But when I build it,  it appears to have a lot of errors about version. So I want to know if the version is correct.

**Comment by 73jn** [comment]
Hello, i use unbuntu 18.04 too...
did you try to launch with this command ?
```
CXXFLAGS="-std=c++0x" ./waf configure
./waf
```

**Comment by 73jn** [comment]
By the way i had to use a previous version of the plc module. Read the [README](https://github.com/73jn/ns3-plc-with-gnosis#readme)

**Comment by zhl606** [comment]
the error is : 
Build failed
 -> task in 'ns3-config-store' failed (exit status 1): 
	{task 139914627456592: cxx xml-config.cc -> xml-config.cc.1.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-fPIC', '-pthread', '-pthread', '-Ibuild', '-I.', '-I/usr/include/gtk-2.0', '-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include', '-I/usr/include/gio-unix-2.0', '-I/usr/include/cairo', '-I/usr/include/pango-1.0', '-I/usr/include/atk-1.0', '-I/usr/include/pixman-1', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/libpng16', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/freetype2', '-I/usr/include/libxml2', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_PACKET_H=1', '-DHAVE_DL=1', '-DSQLITE3=1', '-DHAVE_IF_TUN_H=1', '-DENABLE_GSL', '../src/config-store/model/xml-config.cc', '-c', '-o', 'src/config-store/model/xml-config.cc.1.o']

**Comment by zhl606** [comment]
`CXXFLAGS="-std=c++0x" ./waf configure  
./waf `
Is this command executed after the build?

**Comment by zhl606** [comment]
'‘CXXFLAGS="-std=c++0x" ./waf configure  ./waf'’ Is this command executed after the build?

**Comment by zhl606** [comment]
'‘CXXFLAGS="-std=c++0x" ./waf configure  ./waf'’ Is this command executed after the build?

**Comment by 73jn** [comment]
First go on [NS-3.15 root](https://github.com/73jn/ns3-plc-with-gnosis/tree/master/ns-3.15).
Then configure
`CXXFLAGS="-std=c++0x" ./waf configure`

and build
`./waf`

**Comment by 73jn** [comment]
I use this [VM with all tools included](https://www.youtube.com/watch?v=Tk6HmdrVmUw), you can download it [here](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa0Vrb05FY2Jrd1Z0enRUUE5ScU8zdWpPcjFQd3xBQ3Jtc0tuMnlURmt3bjl4VzQ5X2gxY0dhWUtFaVhWZjlPLWoyY2xkTUZfRms4OVZtX2FDREVzT05CcFRKTlNSd05mMk04a2hmNmZxUGJSTUpId09jMWZ0d0ljNmpBbXhNYUx2TjN6XzJIakZTV18zUlJzVUg3dw&q=http%3A%2F%2Fwww.mediafire.com%2Ffile%2F3itf14zxb7gclp4%2FUbuntu1804.rar)

**Comment by zhl606** [comment]
Thank you! I will try it !

**Comment by zhl606** [comment]
When i execute this command "CXXFLAGS="-std=c++0x" ./waf configure ./waf" , modules built successfully.
But when i run "./waf  --run hello-simulator" , I encounter the same error.
The download link you provided for the virtual machine is for ns3.25, does plc-gnosis work properly with ns3.25?

**Comment by 73jn** [comment]
I couldn't get NS-3.25 to work with the PLC-GNOSIS...
Only with NS-3.15..
But if you managed to compile, it's good news!
Now you have to launch PLC-GNOSIS with Qt version 4.8

**Comment by zhl606** [comment]
But I'm wondering if this means I didn't install ns3.15 successfully, because I can't run hello-simulator successfully.

**Comment by zhl606** [comment]
Hello, I would like to ask you what visualization you are using for your current plc module, pyviz, netanim or plc-gnosis?

**Comment by 73jn** [comment]
Plc-Gnosis

**Comment by zhl606** [comment]
Thank you for your reply, how did you use the ns-3gui, for example how to establish the relationship between the topology diagram of the gui and the code, I didn't find any related resources on the internet, thanks!
